import { UpdatedNewsDataInterface } from './types'

export const CarouselData: UpdatedNewsDataInterface[] = [
  {
    imageURL: '/images/home/image-1.png',
    title: 'Introduction to JavaScript for the beginners',
    link: '#',
    ButtonText: 'Read More',
    date: '06 Nov,2022',
    width: 500,
    height: 500,
  },
  {
    imageURL: '/images/home/image-2.png',
    title: 'Introduction to JavaScript for the beginners',
    link: '#',
    ButtonText: 'Read More',
    date: '06 Nov,2022',
    width: 500,
    height: 500,
  },
  {
    imageURL: '/images/home/image-3.png',
    title: 'Introduction to JavaScript for the beginners',
    link: '#',
    ButtonText: 'Read More',
    date: '06 Nov,2022',
    width: 500,
    height: 500,
  },
  {
    imageURL: '/images/home/image-4.png',
    title: 'Introduction to JavaScript for the beginners',
    link: '#',
    ButtonText: 'Read More',
    date: '06 Nov,2022',
    width: 500,
    height: 500,
  },
  {
    imageURL: '/images/home/image-4.png',
    title: 'Introduction to JavaScript for the beginners',
    link: '#',
    ButtonText: 'Read More',
    date: '06 Nov,2022',
    width: 500,
    height: 500,
  },
  {
    imageURL: '/images/home/image-1.png',
    title: 'Introduction to JavaScript for the beginners',
    link: '#',
    ButtonText: 'Read More',
    date: '06 Nov,2022',
    width: 500,
    height: 500,
  },
  {
    imageURL: '/images/home/image-2.png',
    title: 'Introduction to JavaScript for the beginners',
    link: '#',
    ButtonText: 'Read More',
    date: '06 Nov,2022',
    width: 500,
    height: 500,
  },
  {
    imageURL: '/images/home/image-3.png',
    title: 'Introduction to JavaScript for the beginners',
    link: '#',
    ButtonText: 'Read More',
    date: '06 Nov,2022',
    width: 500,
    height: 500,
  },
  {
    imageURL: '/images/home/image-4.png',
    title: 'Introduction to JavaScript for the beginners',
    link: '#',
    ButtonText: 'Read More',
    date: '06 Nov,2022',
    width: 500,
    height: 500,
  },
  {
    imageURL: '/images/home/image-4.png',
    title: 'Introduction to JavaScript for the beginners',
    link: '#',
    ButtonText: 'Read More',
    date: '06 Nov,2022',
    width: 500,
    height: 500,
  },
]
