export const routes = {
  home: '/',
  about: '/about',
  vision: '/vision',
  trustees: '/trustees',
  founder: '/founder',
  career: '/career',
  calendar: '/calendar',
  courseTuitionFees: '/course-tuition-fees',
  academicPolicies: '/academic-policies',
  offeredDegrees: '/offered-degrees',
  allEvents: '/all-events',
  viceChancellor: '/vice-chancellor',
  allNews: '/all-news',
  newsDetails: '/news-details',
  campusLife: '/campus-life',
  convocation: '/convocation',
  gallery: '/gallery',
}
